export const TODOACTIONS = {
    CREATE_TODO: 'CREATE_TODO',
    CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
    DELETE_TODO: "DELETE_TODO",

    //users
    GET_USERS: "GET_USERS",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    CREATE_USER: "CREATE_USER",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    DELETE_USER: "DELETE_USER",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS"

}